// ********RoostGPT********
/*
Test generated by RoostGPT for test rest-assuredProductAPI using AI Type Open AI and AI Model gpt-4

Test generated for /cancelProductOrder/{order.Id}_post for http method type POST in rest-assured framework

RoostTestHash=284cdcff34


*/

// ********RoostGPT********

// Make sure the file "cancelProductOrder_order.IdPostTest.csv" exists in the path "src/test/java/com/example/RoostTest/"
TestdataLoader dataloader = new TestdataLoader();
String[] envVarsList = {"order.Id", "BASE_URL"};
envList = dataloader.load("src/test/java/com/example/RoostTest/cancelProductOrder_order.IdPostTest.csv", envVarsList);
