// ********RoostGPT********
/*
Test generated by RoostGPT for test rest-assuredProductAPI using AI Type Open AI and AI Model gpt-4

Test generated for /city/{stateAbreviation}_get for http method type GET in rest-assured framework

RoostTestHash=9fe0a02efa


*/

// ********RoostGPT********

@Test  
public void cityStateAbreviationGet_Test() {
    Integer testNumber = 1;
    for (Map<String, String> testData : envList) {
        RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): testData.get("BASE_URL");  
        JSONObject requestBodyObject = new JSONObject();
        if(testData.get("RequestBody") != null){
            requestBodyObject = new JSONObject(testData.get("RequestBody"));
        }
        Response responseObj = given()
        .pathParam("stateAbreviation", testData.get("stateAbreviation") != null ? testData.get("stateAbreviation") : "")
        .when()
        .get("/city/{stateAbreviation}")  
        .then() 
        .extract().response(); 

        String contentType = responseObj.getContentType();
        if(contentType == null){
            System.out.println("Response content type is null");
            continue;
        }
        // Rest of the code is same as above...
    }
}
