// ********RoostGPT********
/*
Test generated by RoostGPT for test rest-assuredProductAPI using AI Type Open AI and AI Model gpt-4

Test generated for /geographicAddress/{addressId}_get for http method type GET in rest-assured framework

RoostTestHash=3800501a9c


*/

// ********RoostGPT********

RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty()) ? testData.get("BASE_URL"): "Default_Base_URL";  
