// ********RoostGPT********
/*
Test generated by RoostGPT for test rest-assuredProductAPI using AI Type Open AI and AI Model gpt-4

Test generated for /productOrder_post for http method type POST in rest-assured framework

RoostTestHash=13e6a9adf7


*/

// ********RoostGPT********

// CHECKSTYLE:OFF
...ignored code...
// CHECKSTYLE:ON
